// Code generated by Kitex v0.12.1. DO NOT EDIT.

package memoirservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	memoir "github.com/hahaha3w/3w3_Ai_Server/rpc-gen/memoir"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GenerateDailyMemoir(ctx context.Context, Req *memoir.GenerateDailyMemoirRequest, callOptions ...callopt.Option) (r *memoir.GenerateMemoirResponse, err error)
	GenerateWeeklyMemoir(ctx context.Context, Req *memoir.GenerateWeeklyMemoirRequest, callOptions ...callopt.Option) (r *memoir.GenerateMemoirResponse, err error)
	GenerateMonthlyMemoir(ctx context.Context, Req *memoir.GenerateMonthlyMemoirRequest, callOptions ...callopt.Option) (r *memoir.GenerateMemoirResponse, err error)
	GetMemoirList(ctx context.Context, Req *memoir.GetMemoirListRequest, callOptions ...callopt.Option) (r *memoir.GetMemoirListResponse, err error)
	GetMemoirDetail(ctx context.Context, Req *memoir.GetMemoirDetailRequest, callOptions ...callopt.Option) (r *memoir.GetMemoirDetailResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMemoirServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMemoirServiceClient struct {
	*kClient
}

func (p *kMemoirServiceClient) GenerateDailyMemoir(ctx context.Context, Req *memoir.GenerateDailyMemoirRequest, callOptions ...callopt.Option) (r *memoir.GenerateMemoirResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateDailyMemoir(ctx, Req)
}

func (p *kMemoirServiceClient) GenerateWeeklyMemoir(ctx context.Context, Req *memoir.GenerateWeeklyMemoirRequest, callOptions ...callopt.Option) (r *memoir.GenerateMemoirResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateWeeklyMemoir(ctx, Req)
}

func (p *kMemoirServiceClient) GenerateMonthlyMemoir(ctx context.Context, Req *memoir.GenerateMonthlyMemoirRequest, callOptions ...callopt.Option) (r *memoir.GenerateMemoirResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateMonthlyMemoir(ctx, Req)
}

func (p *kMemoirServiceClient) GetMemoirList(ctx context.Context, Req *memoir.GetMemoirListRequest, callOptions ...callopt.Option) (r *memoir.GetMemoirListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMemoirList(ctx, Req)
}

func (p *kMemoirServiceClient) GetMemoirDetail(ctx context.Context, Req *memoir.GetMemoirDetailRequest, callOptions ...callopt.Option) (r *memoir.GetMemoirDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMemoirDetail(ctx, Req)
}
