// Code generated by Kitex v0.12.3. DO NOT EDIT.

package memoirservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	"github.com/hahaha3w/3w3_Ai_Server/rpc-gen/memoir"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenerateMemoir": kitex.NewMethodInfo(
		generateMemoirHandler,
		newGenerateMemoirArgs,
		newGenerateMemoirResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetMemoirList": kitex.NewMethodInfo(
		getMemoirListHandler,
		newGetMemoirListArgs,
		newGetMemoirListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetMemoirDetail": kitex.NewMethodInfo(
		getMemoirDetailHandler,
		newGetMemoirDetailArgs,
		newGetMemoirDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteMemoir": kitex.NewMethodInfo(
		deleteMemoirHandler,
		newDeleteMemoirArgs,
		newDeleteMemoirResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	memoirServiceServiceInfo                = NewServiceInfo()
	memoirServiceServiceInfoForClient       = NewServiceInfoForClient()
	memoirServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return memoirServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return memoirServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return memoirServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MemoirService"
	handlerType := (*memoir.MemoirService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "memoir",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func generateMemoirHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(memoir.GenerateMemoirRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(memoir.MemoirService).GenerateMemoir(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GenerateMemoirArgs:
		success, err := handler.(memoir.MemoirService).GenerateMemoir(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GenerateMemoirResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGenerateMemoirArgs() interface{} {
	return &GenerateMemoirArgs{}
}

func newGenerateMemoirResult() interface{} {
	return &GenerateMemoirResult{}
}

type GenerateMemoirArgs struct {
	Req *memoir.GenerateMemoirRequest
}

func (p *GenerateMemoirArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(memoir.GenerateMemoirRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GenerateMemoirArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GenerateMemoirArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GenerateMemoirArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenerateMemoirArgs) Unmarshal(in []byte) error {
	msg := new(memoir.GenerateMemoirRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenerateMemoirArgs_Req_DEFAULT *memoir.GenerateMemoirRequest

func (p *GenerateMemoirArgs) GetReq() *memoir.GenerateMemoirRequest {
	if !p.IsSetReq() {
		return GenerateMemoirArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenerateMemoirArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenerateMemoirArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenerateMemoirResult struct {
	Success *memoir.GenerateMemoirResponse
}

var GenerateMemoirResult_Success_DEFAULT *memoir.GenerateMemoirResponse

func (p *GenerateMemoirResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(memoir.GenerateMemoirResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GenerateMemoirResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GenerateMemoirResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GenerateMemoirResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenerateMemoirResult) Unmarshal(in []byte) error {
	msg := new(memoir.GenerateMemoirResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenerateMemoirResult) GetSuccess() *memoir.GenerateMemoirResponse {
	if !p.IsSetSuccess() {
		return GenerateMemoirResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenerateMemoirResult) SetSuccess(x interface{}) {
	p.Success = x.(*memoir.GenerateMemoirResponse)
}

func (p *GenerateMemoirResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenerateMemoirResult) GetResult() interface{} {
	return p.Success
}

func getMemoirListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(memoir.GetMemoirListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(memoir.MemoirService).GetMemoirList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetMemoirListArgs:
		success, err := handler.(memoir.MemoirService).GetMemoirList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetMemoirListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetMemoirListArgs() interface{} {
	return &GetMemoirListArgs{}
}

func newGetMemoirListResult() interface{} {
	return &GetMemoirListResult{}
}

type GetMemoirListArgs struct {
	Req *memoir.GetMemoirListRequest
}

func (p *GetMemoirListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(memoir.GetMemoirListRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetMemoirListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetMemoirListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetMemoirListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetMemoirListArgs) Unmarshal(in []byte) error {
	msg := new(memoir.GetMemoirListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetMemoirListArgs_Req_DEFAULT *memoir.GetMemoirListRequest

func (p *GetMemoirListArgs) GetReq() *memoir.GetMemoirListRequest {
	if !p.IsSetReq() {
		return GetMemoirListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetMemoirListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetMemoirListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetMemoirListResult struct {
	Success *memoir.GetMemoirListResponse
}

var GetMemoirListResult_Success_DEFAULT *memoir.GetMemoirListResponse

func (p *GetMemoirListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(memoir.GetMemoirListResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetMemoirListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetMemoirListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetMemoirListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetMemoirListResult) Unmarshal(in []byte) error {
	msg := new(memoir.GetMemoirListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetMemoirListResult) GetSuccess() *memoir.GetMemoirListResponse {
	if !p.IsSetSuccess() {
		return GetMemoirListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetMemoirListResult) SetSuccess(x interface{}) {
	p.Success = x.(*memoir.GetMemoirListResponse)
}

func (p *GetMemoirListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetMemoirListResult) GetResult() interface{} {
	return p.Success
}

func getMemoirDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(memoir.GetMemoirDetailRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(memoir.MemoirService).GetMemoirDetail(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetMemoirDetailArgs:
		success, err := handler.(memoir.MemoirService).GetMemoirDetail(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetMemoirDetailResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetMemoirDetailArgs() interface{} {
	return &GetMemoirDetailArgs{}
}

func newGetMemoirDetailResult() interface{} {
	return &GetMemoirDetailResult{}
}

type GetMemoirDetailArgs struct {
	Req *memoir.GetMemoirDetailRequest
}

func (p *GetMemoirDetailArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(memoir.GetMemoirDetailRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetMemoirDetailArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetMemoirDetailArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetMemoirDetailArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetMemoirDetailArgs) Unmarshal(in []byte) error {
	msg := new(memoir.GetMemoirDetailRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetMemoirDetailArgs_Req_DEFAULT *memoir.GetMemoirDetailRequest

func (p *GetMemoirDetailArgs) GetReq() *memoir.GetMemoirDetailRequest {
	if !p.IsSetReq() {
		return GetMemoirDetailArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetMemoirDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetMemoirDetailArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetMemoirDetailResult struct {
	Success *memoir.GetMemoirDetailResponse
}

var GetMemoirDetailResult_Success_DEFAULT *memoir.GetMemoirDetailResponse

func (p *GetMemoirDetailResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(memoir.GetMemoirDetailResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetMemoirDetailResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetMemoirDetailResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetMemoirDetailResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetMemoirDetailResult) Unmarshal(in []byte) error {
	msg := new(memoir.GetMemoirDetailResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetMemoirDetailResult) GetSuccess() *memoir.GetMemoirDetailResponse {
	if !p.IsSetSuccess() {
		return GetMemoirDetailResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetMemoirDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*memoir.GetMemoirDetailResponse)
}

func (p *GetMemoirDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetMemoirDetailResult) GetResult() interface{} {
	return p.Success
}

func deleteMemoirHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(memoir.DeleteMemoirRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(memoir.MemoirService).DeleteMemoir(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteMemoirArgs:
		success, err := handler.(memoir.MemoirService).DeleteMemoir(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteMemoirResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteMemoirArgs() interface{} {
	return &DeleteMemoirArgs{}
}

func newDeleteMemoirResult() interface{} {
	return &DeleteMemoirResult{}
}

type DeleteMemoirArgs struct {
	Req *memoir.DeleteMemoirRequest
}

func (p *DeleteMemoirArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(memoir.DeleteMemoirRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteMemoirArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteMemoirArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteMemoirArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteMemoirArgs) Unmarshal(in []byte) error {
	msg := new(memoir.DeleteMemoirRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteMemoirArgs_Req_DEFAULT *memoir.DeleteMemoirRequest

func (p *DeleteMemoirArgs) GetReq() *memoir.DeleteMemoirRequest {
	if !p.IsSetReq() {
		return DeleteMemoirArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteMemoirArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteMemoirArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteMemoirResult struct {
	Success *memoir.DeleteMemoirResponse
}

var DeleteMemoirResult_Success_DEFAULT *memoir.DeleteMemoirResponse

func (p *DeleteMemoirResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(memoir.DeleteMemoirResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteMemoirResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteMemoirResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteMemoirResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteMemoirResult) Unmarshal(in []byte) error {
	msg := new(memoir.DeleteMemoirResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteMemoirResult) GetSuccess() *memoir.DeleteMemoirResponse {
	if !p.IsSetSuccess() {
		return DeleteMemoirResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteMemoirResult) SetSuccess(x interface{}) {
	p.Success = x.(*memoir.DeleteMemoirResponse)
}

func (p *DeleteMemoirResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteMemoirResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenerateMemoir(ctx context.Context, Req *memoir.GenerateMemoirRequest) (r *memoir.GenerateMemoirResponse, err error) {
	var _args GenerateMemoirArgs
	_args.Req = Req
	var _result GenerateMemoirResult
	if err = p.c.Call(ctx, "GenerateMemoir", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMemoirList(ctx context.Context, Req *memoir.GetMemoirListRequest) (r *memoir.GetMemoirListResponse, err error) {
	var _args GetMemoirListArgs
	_args.Req = Req
	var _result GetMemoirListResult
	if err = p.c.Call(ctx, "GetMemoirList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMemoirDetail(ctx context.Context, Req *memoir.GetMemoirDetailRequest) (r *memoir.GetMemoirDetailResponse, err error) {
	var _args GetMemoirDetailArgs
	_args.Req = Req
	var _result GetMemoirDetailResult
	if err = p.c.Call(ctx, "GetMemoirDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteMemoir(ctx context.Context, Req *memoir.DeleteMemoirRequest) (r *memoir.DeleteMemoirResponse, err error) {
	var _args DeleteMemoirArgs
	_args.Req = Req
	var _result DeleteMemoirResult
	if err = p.c.Call(ctx, "DeleteMemoir", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
