// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0
// source: idl/memoir.proto

package memoir

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Memoir_Type int32

const (
	Memoir_DAILY   Memoir_Type = 0
	Memoir_WEEKLY  Memoir_Type = 1
	Memoir_MONTHLY Memoir_Type = 2
	Memoir_CUSTOM  Memoir_Type = 3
)

// Enum value maps for Memoir_Type.
var (
	Memoir_Type_name = map[int32]string{
		0: "DAILY",
		1: "WEEKLY",
		2: "MONTHLY",
		3: "CUSTOM",
	}
	Memoir_Type_value = map[string]int32{
		"DAILY":   0,
		"WEEKLY":  1,
		"MONTHLY": 2,
		"CUSTOM":  3,
	}
)

func (x Memoir_Type) Enum() *Memoir_Type {
	p := new(Memoir_Type)
	*p = x
	return p
}

func (x Memoir_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Memoir_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_memoir_proto_enumTypes[0].Descriptor()
}

func (Memoir_Type) Type() protoreflect.EnumType {
	return &file_idl_memoir_proto_enumTypes[0]
}

func (x Memoir_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Memoir_Type.Descriptor instead.
func (Memoir_Type) EnumDescriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{0, 0}
}

type Memoir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId      string      `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title       string      `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content     string      `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CharacterId string      `protobuf:"bytes,5,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Type        Memoir_Type `protobuf:"varint,6,opt,name=type,proto3,enum=memoir.Memoir_Type" json:"type,omitempty"`
	StartDate   string      `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate     string      `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CreatedAt   string      `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Memoir) Reset() {
	*x = Memoir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_memoir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Memoir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memoir) ProtoMessage() {}

func (x *Memoir) ProtoReflect() protoreflect.Message {
	mi := &file_idl_memoir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memoir.ProtoReflect.Descriptor instead.
func (*Memoir) Descriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{0}
}

func (x *Memoir) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Memoir) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Memoir) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Memoir) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memoir) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *Memoir) GetType() Memoir_Type {
	if x != nil {
		return x.Type
	}
	return Memoir_DAILY
}

func (x *Memoir) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Memoir) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Memoir) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GenerateDailyMemoirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CharacterId string `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Date        string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // 指定日期，格式YYYY-MM-DD
}

func (x *GenerateDailyMemoirRequest) Reset() {
	*x = GenerateDailyMemoirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_memoir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDailyMemoirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDailyMemoirRequest) ProtoMessage() {}

func (x *GenerateDailyMemoirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_memoir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDailyMemoirRequest.ProtoReflect.Descriptor instead.
func (*GenerateDailyMemoirRequest) Descriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateDailyMemoirRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateDailyMemoirRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GenerateDailyMemoirRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GenerateWeeklyMemoirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CharacterId string `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	StartDate   string `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 周起始日期，格式YYYY-MM-DD
}

func (x *GenerateWeeklyMemoirRequest) Reset() {
	*x = GenerateWeeklyMemoirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_memoir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateWeeklyMemoirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWeeklyMemoirRequest) ProtoMessage() {}

func (x *GenerateWeeklyMemoirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_memoir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWeeklyMemoirRequest.ProtoReflect.Descriptor instead.
func (*GenerateWeeklyMemoirRequest) Descriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateWeeklyMemoirRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateWeeklyMemoirRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GenerateWeeklyMemoirRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

type GenerateMonthlyMemoirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CharacterId string `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	YearMonth   string `protobuf:"bytes,3,opt,name=year_month,json=yearMonth,proto3" json:"year_month,omitempty"` // 月份，格式YYYY-MM
}

func (x *GenerateMonthlyMemoirRequest) Reset() {
	*x = GenerateMonthlyMemoirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_memoir_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMonthlyMemoirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMonthlyMemoirRequest) ProtoMessage() {}

func (x *GenerateMonthlyMemoirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_memoir_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMonthlyMemoirRequest.ProtoReflect.Descriptor instead.
func (*GenerateMonthlyMemoirRequest) Descriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateMonthlyMemoirRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateMonthlyMemoirRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GenerateMonthlyMemoirRequest) GetYearMonth() string {
	if x != nil {
		return x.YearMonth
	}
	return ""
}

type GenerateMemoirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Memoir   *Memoir `protobuf:"bytes,2,opt,name=memoir,proto3" json:"memoir,omitempty"`
	ErrorMsg string  `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
}

func (x *GenerateMemoirResponse) Reset() {
	*x = GenerateMemoirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_memoir_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMemoirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMemoirResponse) ProtoMessage() {}

func (x *GenerateMemoirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_memoir_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMemoirResponse.ProtoReflect.Descriptor instead.
func (*GenerateMemoirResponse) Descriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateMemoirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateMemoirResponse) GetMemoir() *Memoir {
	if x != nil {
		return x.Memoir
	}
	return nil
}

func (x *GenerateMemoirResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetMemoirListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type      Memoir_Type `protobuf:"varint,2,opt,name=type,proto3,enum=memoir.Memoir_Type" json:"type,omitempty"`   // 可选过滤条件
	StartDate string      `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 可选，开始日期
	EndDate   string      `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 可选，结束日期
	Page      int32       `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int32       `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *GetMemoirListRequest) Reset() {
	*x = GetMemoirListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_memoir_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemoirListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoirListRequest) ProtoMessage() {}

func (x *GetMemoirListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_memoir_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoirListRequest.ProtoReflect.Descriptor instead.
func (*GetMemoirListRequest) Descriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{5}
}

func (x *GetMemoirListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMemoirListRequest) GetType() Memoir_Type {
	if x != nil {
		return x.Type
	}
	return Memoir_DAILY
}

func (x *GetMemoirListRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetMemoirListRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetMemoirListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMemoirListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMemoirListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memoirs []*Memoir `protobuf:"bytes,1,rep,name=memoirs,proto3" json:"memoirs,omitempty"`
	Total   int32     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetMemoirListResponse) Reset() {
	*x = GetMemoirListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_memoir_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemoirListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoirListResponse) ProtoMessage() {}

func (x *GetMemoirListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_memoir_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoirListResponse.ProtoReflect.Descriptor instead.
func (*GetMemoirListResponse) Descriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{6}
}

func (x *GetMemoirListResponse) GetMemoirs() []*Memoir {
	if x != nil {
		return x.Memoirs
	}
	return nil
}

func (x *GetMemoirListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetMemoirDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoirId string `protobuf:"bytes,1,opt,name=memoir_id,json=memoirId,proto3" json:"memoir_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetMemoirDetailRequest) Reset() {
	*x = GetMemoirDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_memoir_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemoirDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoirDetailRequest) ProtoMessage() {}

func (x *GetMemoirDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_memoir_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoirDetailRequest.ProtoReflect.Descriptor instead.
func (*GetMemoirDetailRequest) Descriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{7}
}

func (x *GetMemoirDetailRequest) GetMemoirId() string {
	if x != nil {
		return x.MemoirId
	}
	return ""
}

func (x *GetMemoirDetailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMemoirDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memoir *Memoir `protobuf:"bytes,1,opt,name=memoir,proto3" json:"memoir,omitempty"`
}

func (x *GetMemoirDetailResponse) Reset() {
	*x = GetMemoirDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_memoir_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemoirDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoirDetailResponse) ProtoMessage() {}

func (x *GetMemoirDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_memoir_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoirDetailResponse.ProtoReflect.Descriptor instead.
func (*GetMemoirDetailResponse) Descriptor() ([]byte, []int) {
	return file_idl_memoir_proto_rawDescGZIP(), []int{8}
}

func (x *GetMemoirDetailResponse) GetMemoir() *Memoir {
	if x != nil {
		return x.Memoir
	}
	return nil
}

var File_idl_memoir_proto protoreflect.FileDescriptor

var file_idl_memoir_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x64, 0x6c, 0x2f, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x22, 0xbe, 0x02, 0x0a, 0x06, 0x4d,
	0x65, 0x6d, 0x6f, 0x69, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x36, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x44,
	0x41, 0x49, 0x4c, 0x59, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x45, 0x45, 0x4b, 0x4c, 0x59,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x4c, 0x59, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x10, 0x03, 0x22, 0x6c, 0x0a, 0x1a, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x4d, 0x65, 0x6d, 0x6f,
	0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x78, 0x0a, 0x1b, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x6c, 0x79, 0x4d, 0x65, 0x6d, 0x6f, 0x69,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44,
	0x61, 0x74, 0x65, 0x22, 0x79, 0x0a, 0x1c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d,
	0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x79, 0x65, 0x61, 0x72, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x79, 0x65, 0x61, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x22, 0x77,
	0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x4d, 0x65, 0x6d, 0x6f,
	0x69, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0xc3, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x6f, 0x69, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72,
	0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x57, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72,
	0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x4e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d,
	0x6f, 0x69, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d,
	0x6f, 0x69, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x69,
	0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x32, 0x87, 0x02, 0x0a, 0x0d, 0x4d, 0x65,
	0x6d, 0x6f, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x12, 0x22, 0x2e,
	0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x69, 0x6c, 0x79, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1c, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x6f, 0x69, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d,
	0x6f, 0x69, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x52, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x1e, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x6f, 0x69, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x69, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x6f, 0x69, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x68, 0x61, 0x68, 0x61, 0x68, 0x61, 0x33, 0x77, 0x2f, 0x33, 0x77, 0x33, 0x5f, 0x41,
	0x69, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x6d, 0x65, 0x6d, 0x6f, 0x69,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_memoir_proto_rawDescOnce sync.Once
	file_idl_memoir_proto_rawDescData = file_idl_memoir_proto_rawDesc
)

func file_idl_memoir_proto_rawDescGZIP() []byte {
	file_idl_memoir_proto_rawDescOnce.Do(func() {
		file_idl_memoir_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_memoir_proto_rawDescData)
	})
	return file_idl_memoir_proto_rawDescData
}

var file_idl_memoir_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idl_memoir_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_idl_memoir_proto_goTypes = []interface{}{
	(Memoir_Type)(0),                     // 0: memoir.Memoir.Type
	(*Memoir)(nil),                       // 1: memoir.Memoir
	(*GenerateDailyMemoirRequest)(nil),   // 2: memoir.GenerateDailyMemoirRequest
	(*GenerateWeeklyMemoirRequest)(nil),  // 3: memoir.GenerateWeeklyMemoirRequest
	(*GenerateMonthlyMemoirRequest)(nil), // 4: memoir.GenerateMonthlyMemoirRequest
	(*GenerateMemoirResponse)(nil),       // 5: memoir.GenerateMemoirResponse
	(*GetMemoirListRequest)(nil),         // 6: memoir.GetMemoirListRequest
	(*GetMemoirListResponse)(nil),        // 7: memoir.GetMemoirListResponse
	(*GetMemoirDetailRequest)(nil),       // 8: memoir.GetMemoirDetailRequest
	(*GetMemoirDetailResponse)(nil),      // 9: memoir.GetMemoirDetailResponse
}
var file_idl_memoir_proto_depIdxs = []int32{
	0, // 0: memoir.Memoir.type:type_name -> memoir.Memoir.Type
	1, // 1: memoir.GenerateMemoirResponse.memoir:type_name -> memoir.Memoir
	0, // 2: memoir.GetMemoirListRequest.type:type_name -> memoir.Memoir.Type
	1, // 3: memoir.GetMemoirListResponse.memoirs:type_name -> memoir.Memoir
	1, // 4: memoir.GetMemoirDetailResponse.memoir:type_name -> memoir.Memoir
	2, // 5: memoir.MemoirService.GenerateMemoir:input_type -> memoir.GenerateDailyMemoirRequest
	6, // 6: memoir.MemoirService.GetMemoirList:input_type -> memoir.GetMemoirListRequest
	8, // 7: memoir.MemoirService.GetMemoirDetail:input_type -> memoir.GetMemoirDetailRequest
	5, // 8: memoir.MemoirService.GenerateMemoir:output_type -> memoir.GenerateMemoirResponse
	7, // 9: memoir.MemoirService.GetMemoirList:output_type -> memoir.GetMemoirListResponse
	9, // 10: memoir.MemoirService.GetMemoirDetail:output_type -> memoir.GetMemoirDetailResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_idl_memoir_proto_init() }
func file_idl_memoir_proto_init() {
	if File_idl_memoir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_memoir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Memoir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_memoir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDailyMemoirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_memoir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateWeeklyMemoirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_memoir_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMonthlyMemoirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_memoir_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMemoirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_memoir_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemoirListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_memoir_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemoirListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_memoir_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemoirDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_memoir_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemoirDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_memoir_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_memoir_proto_goTypes,
		DependencyIndexes: file_idl_memoir_proto_depIdxs,
		EnumInfos:         file_idl_memoir_proto_enumTypes,
		MessageInfos:      file_idl_memoir_proto_msgTypes,
	}.Build()
	File_idl_memoir_proto = out.File
	file_idl_memoir_proto_rawDesc = nil
	file_idl_memoir_proto_goTypes = nil
	file_idl_memoir_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.12.1. DO NOT EDIT.

type MemoirService interface {
	GenerateMemoir(ctx context.Context, req *GenerateDailyMemoirRequest) (res *GenerateMemoirResponse, err error)
	GetMemoirList(ctx context.Context, req *GetMemoirListRequest) (res *GetMemoirListResponse, err error)
	GetMemoirDetail(ctx context.Context, req *GetMemoirDetailRequest) (res *GetMemoirDetailResponse, err error)
}
