version: "3"
services:
  nats:
    image: nats
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -DV
    restart: unless-stopped
#  consul:
#    image: "consul:1.15.4"
#    ports:
#      - "8500:8500"
  mysql:
    image: 'mysql:8'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
