services:
  nats:
    image: nats
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -DV
    restart: always
  consul:
    image: "consul:1.15.4"
    ports:
      - "8500:8500"
  mysql:
    image: 'mysql:8'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379

    command: redis-server --requirepass 12345678
