// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hahaha3w/3w3_Ai_Server/memoir/internal/core"
	"github.com/hahaha3w/3w3_Ai_Server/memoir/internal/delivery"
	"github.com/hahaha3w/3w3_Ai_Server/memoir/internal/repo"
	"github.com/hahaha3w/3w3_Ai_Server/memoir/internal/usecase"
)

// Injectors from wire.go:

func wireApp() *delivery.MemoirDelivery {
	context := core.NewContext()
	db := core.NewDB(context)
	mysqlMemoirRepo := repo.NewMysqlMemoirRepo(db)
	client := core.NewRedis(context)
	concreteMemoirUsecase := usecase.NewConcreteMemoirUsecase(mysqlMemoirRepo, client)
	memoirDelivery := delivery.New(mysqlMemoirRepo, concreteMemoirUsecase)
	return memoirDelivery
}
