// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hahaha3w/3w3_Ai_Server/chat/internal/core"
	"github.com/hahaha3w/3w3_Ai_Server/chat/internal/delivery"
	"github.com/hahaha3w/3w3_Ai_Server/chat/internal/mq"
	"github.com/hahaha3w/3w3_Ai_Server/chat/internal/repo"
	"github.com/hahaha3w/3w3_Ai_Server/chat/internal/usecase"
)

// Injectors from wire.go:

func wireApp() *delivery.ChatDelivery {
	context := core.NewContext()
	db := core.NewDB(context)
	chatRepo := repo.NewChatRepo(db)
	conn := core.NewMQ()
	chatMQ := mq.NewChatMQ(conn, chatRepo)
	chatUsecase := usecase.NewChatUsecase(chatRepo, chatMQ)
	chatDelivery := delivery.NewChatDelivery(chatUsecase, chatMQ)
	return chatDelivery
}
