// Code generated by Kitex v0.12.1. DO NOT EDIT.
package chatservice

import (
	server "github.com/cloudwego/kitex/server"
	chat "github.com/hahaha3w/3w3_Ai_Server/rpc-gen/chat"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler chat.ChatService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler chat.ChatService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
