// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hahaha3w/3w3_Ai_Server/activity/internal/core"
	"github.com/hahaha3w/3w3_Ai_Server/activity/internal/delivery"
	"github.com/hahaha3w/3w3_Ai_Server/activity/internal/repo"
	"github.com/hahaha3w/3w3_Ai_Server/activity/internal/usecase"
)

// Injectors from wire.go:

func wireApp() *delivery.ActivityDelivery {
	context := core.NewContext()
	db := core.NewDB(context)
	mysqlActivityRepo := repo.NewMysqlActivityRepo(db)
	client := core.NewRedis(context)
	concreteActivityUsecase := usecase.NewConcreteActivityUsecase(mysqlActivityRepo, client)
	activityDelivery := delivery.New(mysqlActivityRepo, concreteActivityUsecase)
	return activityDelivery
}
