name: activity_workflow.yml
on:
  push:
    tags:
      - activity_v**
  workflow_dispatch:


jobs:
  Deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./app/activity
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Docker Image Url
        id: image
        env:
          URL: xyq777/ai-biography-activity
        run: |
          echo LATEST=${URL}:latest >> $GITHUB_OUTPUT
          echo VERSION=${URL}:${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          cd ./scripts
          sh ./build.sh
          cd ..


      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
          --tag ${{ steps.image.outputs.VERSION }} \
          --tag ${{ steps.image.outputs.LATEST }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: |
          docker push ${{ steps.image.outputs.VERSION }}
          docker push ${{ steps.image.outputs.LATEST }}

      - name: Update Deployment
        uses: MultiMx/K8sSetImageAction@v0.6
        with:
          backend: 'https://rancher.ncuos.com'
          token: ${{ secrets.RANCHER_TOKEN }}
          namespace: 'default'
          workload: 'ai-biography-activity'
          image: ${{ steps.image.outputs.VERSION }}

